import type { ComponentType } from 'react';
import {
  BookingConfirmPage,
  BookingReceiptPage,
  BookingsListPage,
  CheckoutPage,
  CommunityWalletPage,
  PaymentMethodsPage,
  WalletHistoryPage,
} from './bookingWallet';
import {
  ChampionBadgePage,
  ChatInboxPage,
  ChatThreadPage,
  NotificationPrefsPage,
  NotificationsCenterPage,
  ProofOfDeliveryPage,
  PublicProfilePage,
  ReviewSubmissionPage,
  TrackingCompletedPage,
  TrackingHomePage,
  TrackingLivePage,
  TrustScorePage,
} from './trackingCommsProfile';
import {
  RequesterBrowseTripsPage,
  RequesterEditRequestPage,
  RequesterMatchDetailPage,
  RequesterPostDeliveryPage,
  RequesterPostSupportPage,
  RequesterRequestDetailPage,
  RequesterRequestsListPage,
  RequesterReviewRequestPage,
  RequesterSelectTypePage,
} from './requester';
import {
  TravelerBrowseRequestsPage,
  TravelerEditTripPage,
  TravelerMatchDetailPage,
  TravelerPayoutsPage,
  TravelerPostTripPage,
  TravelerReviewTripPage,
  TravelerSocialImpactPage,
  TravelerTripDetailPage,
  TravelerTripsListPage,
} from './traveler';
import {
  SettingsHelpCenterPage,
  SettingsHelpCommunityPage,
  SettingsHelpContactPage,
  SettingsHelpTicketsPage,
  SettingsMyProfilePage,
  SettingsPrivacyPage,
  SettingsSecurityPage,
} from './accountSettings';

/** Maps `APP_SCREEN_CATALOG` paths to screen components. */
export const APP_SCREEN_REGISTRY: Record<string, ComponentType> = {
  'traveler/trips/new': TravelerPostTripPage,
  'traveler/social-impact': TravelerSocialImpactPage,
  'traveler/trips/review': TravelerReviewTripPage,
  'traveler/trips': TravelerTripsListPage,
  'traveler/trips/detail': TravelerTripDetailPage,
  'traveler/trips/edit': TravelerEditTripPage,
  'traveler/matches/detail': TravelerMatchDetailPage,
  'traveler/browse/requests': TravelerBrowseRequestsPage,
  'traveler/payouts': TravelerPayoutsPage,
  'requester/select-type': RequesterSelectTypePage,
  'requester/support/new': RequesterPostSupportPage,
  'requester/delivery/new': RequesterPostDeliveryPage,
  'requester/requests/review': RequesterReviewRequestPage,
  'requester/requests': RequesterRequestsListPage,
  'requester/requests/detail': RequesterRequestDetailPage,
  'requester/requests/edit': RequesterEditRequestPage,
  'requester/browse/trips': RequesterBrowseTripsPage,
  'requester/matches/detail': RequesterMatchDetailPage,
  'booking/confirm': BookingConfirmPage,
  'booking/receipt': BookingReceiptPage,
  bookings: BookingsListPage,
  checkout: CheckoutPage,
  'wallet/history': WalletHistoryPage,
  'wallet/payment-methods': PaymentMethodsPage,
  'wallet/community': CommunityWalletPage,
  'tracking/live': TrackingLivePage,
  'tracking/completed': TrackingCompletedPage,
  tracking: TrackingHomePage,
  'tracking/pod': ProofOfDeliveryPage,
  chat: ChatInboxPage,
  'chat/thread': ChatThreadPage,
  'settings/notifications': NotificationPrefsPage,
  'settings/my-profile': SettingsMyProfilePage,
  'settings/security': SettingsSecurityPage,
  'settings/privacy': SettingsPrivacyPage,
  'settings/help-center': SettingsHelpCenterPage,
  'settings/help-tickets': SettingsHelpTicketsPage,
  'settings/help-community': SettingsHelpCommunityPage,
  'settings/help-contact': SettingsHelpContactPage,
  notifications: NotificationsCenterPage,
  'profile/badge': ChampionBadgePage,
  'reviews/new': ReviewSubmissionPage,
  'profile/public': PublicProfilePage,
  'trust-score': TrustScorePage,
};
